{
 "title": "Sui-Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostnames",
    "query": "SELECT DISTINCT hostname FROM \"testDB\".\"suimon\" WHERE time > ago(15m) "
   }
  ]
 },
 "panels": [
  { "title": "Validator Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Highest Syncd Checkpoint",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT highest_synced_checkpoint, hostname, bin(time, 1m) AS binned_time\nFROM $__database.$__table\nWHERE time > ago(1h) and hostname='$hostnames'\nORDER BY binned_time",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Certs Created",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT certificates_created, hostname, bin(time, 1m) AS binned_time\nFROM $__database.$__table\nWHERE time > ago(1h) and hostname='$hostnames'\nORDER BY binned_time",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Current Round",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT current_round, hostname, bin(time, 1m) AS binned_time\nFROM $__database.$__table\nWHERE time > ago(1h) and hostname='$hostnames'\nORDER BY binned_time",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Epoch Time Left",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT epoch_time_left, hostname, bin(time, 1m) AS binned_time\nFROM $__database.$__table\nWHERE time > ago(1h) and hostname='$hostnames'\nORDER BY binned_time",
     "table": "\"suimon\""
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT memory\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table WHERE hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "DB Disk",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT db_disk\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table WHERE hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT disk\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table where hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT cpu\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table where hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Swap",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT swap\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table where hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT uptime\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table where hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Network In/Out MB/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT hostname, avg(net_in) as netIn, avg(net_out) as netOut, bin(time, 1m) AS binned_time\n  FROM $__database.$__table\nWHERE time > ago(3h) and hostname='$hostnames'\n GROUP BY hostname, bin(time, 1m)\n ORDER BY binned_time",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "SystemStats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT hostname, avg(cpu) AS avg_cpu,\n       avg(memory) AS avg_memory, avg(disk) AS avg_disk, avg(db_disk) as avg_dbdisk,\n       avg(swap) AS avg_swap, bin(time, 1m) AS binned_time\n  FROM $__database.$__table\nWHERE time > ago(3h) and hostname='$hostnames'\n GROUP BY hostname, bin(time, 1m)\n ORDER BY binned_time",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Disk Utils",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT avg(db_disk) AS avg_dbdisk,\n       avg(disk) AS avg_disk, bin(time, 1m) AS binned_time\n  FROM $__database.$__table\n  WHERE time > ago(3h) and hostname='$hostnames'\n GROUP BY hostname, bin(time, 1m)\n ORDER BY binned_time",
     "table": "\"suimon\""
    }
   ]
  },
  { "title": "Stake Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT curr_epoch\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table where hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Current Staked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT curr_stake\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table where hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Staked Amount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT MAX(curr_stake) as stake, bin(time, 24h) AS binned_time\nFROM testDB.suimon\nWHERE time > ago(14d) and hostname='$hostnames'\nGROUP BY bin(time, 24h)\nORDER BY binned_time",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Self-Stake Total Trend",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT MAX(stake_total/1000) as selfstake, curr_epoch\nFROM testDB.suimon\nWHERE time > ago(7d) and hostname='$hostnames'\nGROUP BY curr_epoch\nORDER BY curr_epoch",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Commission",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT commission\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table where hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "SelfStaked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT stake_total/1000\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table where hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Current Round",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT current_round\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table where hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Highest Syncd Checkpt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT highest_synced_checkpoint\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table where hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Last Exec Checkpt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT last_executed_checkpoint\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table where hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Certs Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT certificates_created\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table where hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Ref Gas Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT gas_price\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table where hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  },
  {
   "title": "Curr Epoch Vtd Gas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"testDB\"",
     "measure": "utilization",
     "rawQuery": "SELECT curr_voted_gas\nFROM $__database.$__table\nWHERE time=(SELECT max(time) FROM $__database.$__table where hostname='$hostnames') and hostname='$hostnames'",
     "table": "\"suimon\""
    }
   ]
  }
 ]
}