payalod = {'Time': '1679081861205',
           'MeasureValues': [
               {'Name': 'cpu', 'Value': '2.6', 'Type': 'DOUBLE'},
               {'Name': 'memory', 'Value': '1.8', 'Type': 'DOUBLE'},
               {'Name': 'swap', 'Value': '0.0', 'Type': 'DOUBLE'},
               {'Name': 'disk', 'Value': '3.5', 'Type': 'DOUBLE'},
               {'Name': 'highest_synced_checkpoint',
                   'Value': 'highest_synced_checkpoint 146836', 'Type': 'DOUBLE'},
               {'Name': 'uptime', 'Value': '74150', 'Type': 'DOUBLE'},
               {'Name': 'curr_epoch', 'Value': '2', 'Type': 'DOUBLE'},
               {'Name': 'gas_price', 'Value': '1000', 'Type': 'DOUBLE'},
               {'Name': 'storage_fund', 'Value': '57724', 'Type': 'DOUBLE'},
               {'Name': 'commission', 'Value': '15.0', 'Type': 'DOUBLE'},
               {'Name': 'curr_voted_gas', 'Value': '1000', 'Type': 'DOUBLE'},
               {'Name': 'next_epoch_voted_gas', 'Value': '1000', 'Type': 'DOUBLE'},
               {'Name': 'curr_stake', 'Value': '30032456603.2478', 'Type': 'DOUBLE'},
               {'Name': 'next_epoch_stake',
                   'Value': '30032456603.2478', 'Type': 'DOUBLE'},
               {'Name': 'voting_power', 'Value': '157', 'Type': 'DOUBLE'},
               {'Name': 'rewards_pool', 'Value': '27588112.760631', 'Type': 'DOUBLE'}]}
