[
    {
        "Time": "1682473044569",
        "MeasureValues": [
            {"Name": "cpu", "Value": "8.4", "Type": "DOUBLE"},
            {"Name": "memory", "Value": "16.4", "Type": "DOUBLE"},
            {"Name": "swap", "Value": "0.3", "Type": "DOUBLE"},
            {"Name": "disk", "Value": "10.4", "Type": "DOUBLE"},
            {"Name": "db_disk", "Value": "49.8", "Type": "DOUBLE"},
            {"Name": "certificates_created", "Value": "2036", "Type": "DOUBLE"},
            {"Name": "current_round", "Value": "25941", "Type": "DOUBLE"},
            {"Name": "highest_synced_checkpoint", "Value": "2109076", "Type": "DOUBLE"},
            {"Name": "last_executed_checkpoint", "Value": "2109076", "Type": "DOUBLE"},
            {
                "Name": "last_executed_checkpoint",
                "Value": "1682473036059",
                "Type": "DOUBLE",
            },
            {"Name": "num_shared_obj_tx", "Value": "34449", "Type": "DOUBLE"},
            {
                "Name": "total_transaction_certificates",
                "Value": "138369",
                "Type": "DOUBLE",
            },
            {"Name": "uptime", "Value": "1275", "Type": "DOUBLE"},
            {"Name": "epoch_time_left", "Value": "72192172.90893555", "Type": "DOUBLE"},
            {"Name": "curr_epoch", "Value": "769", "Type": "DOUBLE"},
            {"Name": "gas_price", "Value": "1000", "Type": "DOUBLE"},
            {"Name": "commission", "Value": "10.0", "Type": "DOUBLE"},
            {"Name": "curr_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "next_epoch_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "curr_stake", "Value": "25175180.982754085", "Type": "DOUBLE"},
            {
                "Name": "next_epoch_stake",
                "Value": "25175396.95940239",
                "Type": "DOUBLE",
            },
            {"Name": "voting_power", "Value": "51", "Type": "DOUBLE"},
            {"Name": "rewards_pool", "Value": "117622.909087535", "Type": "DOUBLE"},
            {"Name": "stake_total", "Value": "13070.019320946", "Type": "DOUBLE"},
        ],
    },
    {
        "Time": "1682473054199",
        "MeasureValues": [
            {"Name": "cpu", "Value": "6.1", "Type": "DOUBLE"},
            {"Name": "memory", "Value": "16.4", "Type": "DOUBLE"},
            {"Name": "swap", "Value": "0.3", "Type": "DOUBLE"},
            {"Name": "disk", "Value": "10.4", "Type": "DOUBLE"},
            {"Name": "db_disk", "Value": "49.8", "Type": "DOUBLE"},
            {"Name": "certificates_created", "Value": "2045", "Type": "DOUBLE"},
            {"Name": "current_round", "Value": "25962", "Type": "DOUBLE"},
            {"Name": "highest_synced_checkpoint", "Value": "2109087", "Type": "DOUBLE"},
            {"Name": "last_executed_checkpoint", "Value": "2109087", "Type": "DOUBLE"},
            {
                "Name": "last_executed_checkpoint",
                "Value": "1682473047065",
                "Type": "DOUBLE",
            },
            {"Name": "num_shared_obj_tx", "Value": "34767", "Type": "DOUBLE"},
            {
                "Name": "total_transaction_certificates",
                "Value": "139538",
                "Type": "DOUBLE",
            },
            {"Name": "uptime", "Value": "1285", "Type": "DOUBLE"},
            {"Name": "epoch_time_left", "Value": "72184521.65283203", "Type": "DOUBLE"},
            {"Name": "rewards_pool", "Value": "117622.909087535", "Type": "DOUBLE"},
            {"Name": "voting_power", "Value": "51", "Type": "DOUBLE"},
            {
                "Name": "next_epoch_stake",
                "Value": "25175396.95940239",
                "Type": "DOUBLE",
            },
            {"Name": "curr_stake", "Value": "25175180.982754085", "Type": "DOUBLE"},
            {"Name": "next_epoch_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "curr_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "commission", "Value": "10.0", "Type": "DOUBLE"},
            {"Name": "gas_price", "Value": "1000", "Type": "DOUBLE"},
            {"Name": "curr_epoch", "Value": "769", "Type": "DOUBLE"},
            {"Name": "stake_total", "Value": "13070019.320946", "Type": "DOUBLE"},
        ],
    },
    {
        "Time": "1682473060295",
        "MeasureValues": [
            {"Name": "cpu", "Value": "6.4", "Type": "DOUBLE"},
            {"Name": "memory", "Value": "16.6", "Type": "DOUBLE"},
            {"Name": "swap", "Value": "0.3", "Type": "DOUBLE"},
            {"Name": "disk", "Value": "10.4", "Type": "DOUBLE"},
            {"Name": "db_disk", "Value": "49.9", "Type": "DOUBLE"},
            {"Name": "certificates_created", "Value": "2055", "Type": "DOUBLE"},
            {"Name": "current_round", "Value": "25974", "Type": "DOUBLE"},
            {"Name": "highest_synced_checkpoint", "Value": "2109094", "Type": "DOUBLE"},
            {"Name": "last_executed_checkpoint", "Value": "2109094", "Type": "DOUBLE"},
            {
                "Name": "last_executed_checkpoint",
                "Value": "1682473056567",
                "Type": "DOUBLE",
            },
            {"Name": "num_shared_obj_tx", "Value": "34889", "Type": "DOUBLE"},
            {
                "Name": "total_transaction_certificates",
                "Value": "140126",
                "Type": "DOUBLE",
            },
            {"Name": "uptime", "Value": "1291", "Type": "DOUBLE"},
            {"Name": "epoch_time_left", "Value": "72178426.39697266", "Type": "DOUBLE"},
            {"Name": "rewards_pool", "Value": "117622.909087535", "Type": "DOUBLE"},
            {"Name": "voting_power", "Value": "51", "Type": "DOUBLE"},
            {
                "Name": "next_epoch_stake",
                "Value": "25175396.95940239",
                "Type": "DOUBLE",
            },
            {"Name": "curr_stake", "Value": "25175180.982754085", "Type": "DOUBLE"},
            {"Name": "next_epoch_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "curr_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "commission", "Value": "10.0", "Type": "DOUBLE"},
            {"Name": "gas_price", "Value": "1000", "Type": "DOUBLE"},
            {"Name": "curr_epoch", "Value": "769", "Type": "DOUBLE"},
            {"Name": "stake_total", "Value": "13070019.320946", "Type": "DOUBLE"},
        ],
    },
    {
        "Time": "1682473066390",
        "MeasureValues": [
            {"Name": "cpu", "Value": "6.7", "Type": "DOUBLE"},
            {"Name": "memory", "Value": "16.8", "Type": "DOUBLE"},
            {"Name": "swap", "Value": "0.3", "Type": "DOUBLE"},
            {"Name": "disk", "Value": "10.4", "Type": "DOUBLE"},
            {"Name": "db_disk", "Value": "49.9", "Type": "DOUBLE"},
            {"Name": "certificates_created", "Value": "2066", "Type": "DOUBLE"},
            {"Name": "current_round", "Value": "25985", "Type": "DOUBLE"},
            {"Name": "highest_synced_checkpoint", "Value": "2109100", "Type": "DOUBLE"},
            {"Name": "last_executed_checkpoint", "Value": "2109100", "Type": "DOUBLE"},
            {
                "Name": "last_executed_checkpoint",
                "Value": "1682473063163",
                "Type": "DOUBLE",
            },
            {"Name": "num_shared_obj_tx", "Value": "35180", "Type": "DOUBLE"},
            {
                "Name": "total_transaction_certificates",
                "Value": "140873",
                "Type": "DOUBLE",
            },
            {"Name": "uptime", "Value": "1297", "Type": "DOUBLE"},
            {"Name": "epoch_time_left", "Value": "72172331.46899414", "Type": "DOUBLE"},
            {"Name": "rewards_pool", "Value": "117622.909087535", "Type": "DOUBLE"},
            {"Name": "voting_power", "Value": "51", "Type": "DOUBLE"},
            {
                "Name": "next_epoch_stake",
                "Value": "25175396.95940239",
                "Type": "DOUBLE",
            },
            {"Name": "curr_stake", "Value": "25175180.982754085", "Type": "DOUBLE"},
            {"Name": "next_epoch_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "curr_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "commission", "Value": "10.0", "Type": "DOUBLE"},
            {"Name": "gas_price", "Value": "1000", "Type": "DOUBLE"},
            {"Name": "curr_epoch", "Value": "769", "Type": "DOUBLE"},
            {"Name": "stake_total", "Value": "13070019.320946", "Type": "DOUBLE"},
        ],
    },
    {
        "Time": "1682473072484",
        "MeasureValues": [
            {"Name": "cpu", "Value": "6.5", "Type": "DOUBLE"},
            {"Name": "memory", "Value": "16.7", "Type": "DOUBLE"},
            {"Name": "swap", "Value": "0.3", "Type": "DOUBLE"},
            {"Name": "disk", "Value": "10.4", "Type": "DOUBLE"},
            {"Name": "db_disk", "Value": "49.8", "Type": "DOUBLE"},
            {"Name": "certificates_created", "Value": "2076", "Type": "DOUBLE"},
            {"Name": "current_round", "Value": "25997", "Type": "DOUBLE"},
            {"Name": "highest_synced_checkpoint", "Value": "2109100", "Type": "DOUBLE"},
            {"Name": "last_executed_checkpoint", "Value": "2109100", "Type": "DOUBLE"},
            {
                "Name": "last_executed_checkpoint",
                "Value": "1682473063163",
                "Type": "DOUBLE",
            },
            {"Name": "num_shared_obj_tx", "Value": "35328", "Type": "DOUBLE"},
            {
                "Name": "total_transaction_certificates",
                "Value": "141574",
                "Type": "DOUBLE",
            },
            {"Name": "uptime", "Value": "1303", "Type": "DOUBLE"},
            {"Name": "epoch_time_left", "Value": "72166236.73706055", "Type": "DOUBLE"},
            {"Name": "rewards_pool", "Value": "117622.909087535", "Type": "DOUBLE"},
            {"Name": "voting_power", "Value": "51", "Type": "DOUBLE"},
            {
                "Name": "next_epoch_stake",
                "Value": "25175396.95940239",
                "Type": "DOUBLE",
            },
            {"Name": "curr_stake", "Value": "25175180.982754085", "Type": "DOUBLE"},
            {"Name": "next_epoch_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "curr_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "commission", "Value": "10.0", "Type": "DOUBLE"},
            {"Name": "gas_price", "Value": "1000", "Type": "DOUBLE"},
            {"Name": "curr_epoch", "Value": "769", "Type": "DOUBLE"},
            {"Name": "stake_total", "Value": "13070019.320946", "Type": "DOUBLE"},
        ],
    },
    {
        "Time": "1682473078579",
        "MeasureValues": [
            {"Name": "cpu", "Value": "5.5", "Type": "DOUBLE"},
            {"Name": "memory", "Value": "16.7", "Type": "DOUBLE"},
            {"Name": "swap", "Value": "0.3", "Type": "DOUBLE"},
            {"Name": "disk", "Value": "10.4", "Type": "DOUBLE"},
            {"Name": "db_disk", "Value": "49.9", "Type": "DOUBLE"},
            {"Name": "certificates_created", "Value": "2083", "Type": "DOUBLE"},
            {"Name": "current_round", "Value": "26006", "Type": "DOUBLE"},
            {"Name": "highest_synced_checkpoint", "Value": "2109108", "Type": "DOUBLE"},
            {"Name": "last_executed_checkpoint", "Value": "2109108", "Type": "DOUBLE"},
            {
                "Name": "last_executed_checkpoint",
                "Value": "1682473071199",
                "Type": "DOUBLE",
            },
            {"Name": "num_shared_obj_tx", "Value": "35564", "Type": "DOUBLE"},
            {
                "Name": "total_transaction_certificates",
                "Value": "142279",
                "Type": "DOUBLE",
            },
            {"Name": "uptime", "Value": "1309", "Type": "DOUBLE"},
            {"Name": "epoch_time_left", "Value": "72160141.93017578", "Type": "DOUBLE"},
            {"Name": "rewards_pool", "Value": "117622.909087535", "Type": "DOUBLE"},
            {"Name": "voting_power", "Value": "51", "Type": "DOUBLE"},
            {
                "Name": "next_epoch_stake",
                "Value": "25175396.95940239",
                "Type": "DOUBLE",
            },
            {"Name": "curr_stake", "Value": "25175180.982754085", "Type": "DOUBLE"},
            {"Name": "next_epoch_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "curr_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "commission", "Value": "10.0", "Type": "DOUBLE"},
            {"Name": "gas_price", "Value": "1000", "Type": "DOUBLE"},
            {"Name": "curr_epoch", "Value": "769", "Type": "DOUBLE"},
            {"Name": "stake_total", "Value": "13070019.320946", "Type": "DOUBLE"},
        ],
    },
    {
        "Time": "1682473084674",
        "MeasureValues": [
            {"Name": "cpu", "Value": "6.0", "Type": "DOUBLE"},
            {"Name": "memory", "Value": "16.8", "Type": "DOUBLE"},
            {"Name": "swap", "Value": "0.3", "Type": "DOUBLE"},
            {"Name": "disk", "Value": "10.4", "Type": "DOUBLE"},
            {"Name": "db_disk", "Value": "49.9", "Type": "DOUBLE"},
            {"Name": "certificates_created", "Value": "2095", "Type": "DOUBLE"},
            {"Name": "current_round", "Value": "26019", "Type": "DOUBLE"},
            {"Name": "highest_synced_checkpoint", "Value": "2109114", "Type": "DOUBLE"},
            {"Name": "last_executed_checkpoint", "Value": "2109114", "Type": "DOUBLE"},
            {
                "Name": "last_executed_checkpoint",
                "Value": "1682473079669",
                "Type": "DOUBLE",
            },
            {"Name": "num_shared_obj_tx", "Value": "35707", "Type": "DOUBLE"},
            {
                "Name": "total_transaction_certificates",
                "Value": "142887",
                "Type": "DOUBLE",
            },
            {"Name": "uptime", "Value": "1315", "Type": "DOUBLE"},
            {"Name": "epoch_time_left", "Value": "72154046.90600586", "Type": "DOUBLE"},
            {"Name": "rewards_pool", "Value": "117622.909087535", "Type": "DOUBLE"},
            {"Name": "voting_power", "Value": "51", "Type": "DOUBLE"},
            {
                "Name": "next_epoch_stake",
                "Value": "25175396.95940239",
                "Type": "DOUBLE",
            },
            {"Name": "curr_stake", "Value": "25175180.982754085", "Type": "DOUBLE"},
            {"Name": "next_epoch_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "curr_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "commission", "Value": "10.0", "Type": "DOUBLE"},
            {"Name": "gas_price", "Value": "1000", "Type": "DOUBLE"},
            {"Name": "curr_epoch", "Value": "769", "Type": "DOUBLE"},
            {"Name": "stake_total", "Value": "13070019.320946", "Type": "DOUBLE"},
        ],
    },
    {
        "Time": "1682473090769",
        "MeasureValues": [
            {"Name": "cpu", "Value": "6.4", "Type": "DOUBLE"},
            {"Name": "memory", "Value": "16.7", "Type": "DOUBLE"},
            {"Name": "swap", "Value": "0.3", "Type": "DOUBLE"},
            {"Name": "disk", "Value": "10.4", "Type": "DOUBLE"},
            {"Name": "db_disk", "Value": "49.9", "Type": "DOUBLE"},
            {"Name": "certificates_created", "Value": "2107", "Type": "DOUBLE"},
            {"Name": "current_round", "Value": "26031", "Type": "DOUBLE"},
            {"Name": "highest_synced_checkpoint", "Value": "2109116", "Type": "DOUBLE"},
            {"Name": "last_executed_checkpoint", "Value": "2109116", "Type": "DOUBLE"},
            {
                "Name": "last_executed_checkpoint",
                "Value": "1682473081717",
                "Type": "DOUBLE",
            },
            {"Name": "num_shared_obj_tx", "Value": "35954", "Type": "DOUBLE"},
            {
                "Name": "total_transaction_certificates",
                "Value": "143645",
                "Type": "DOUBLE",
            },
            {"Name": "uptime", "Value": "1321", "Type": "DOUBLE"},
            {"Name": "epoch_time_left", "Value": "72147953.2590332", "Type": "DOUBLE"},
            {"Name": "rewards_pool", "Value": "117622.909087535", "Type": "DOUBLE"},
            {"Name": "voting_power", "Value": "51", "Type": "DOUBLE"},
            {
                "Name": "next_epoch_stake",
                "Value": "25175396.95940239",
                "Type": "DOUBLE",
            },
            {"Name": "curr_stake", "Value": "25175180.982754085", "Type": "DOUBLE"},
            {"Name": "next_epoch_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "curr_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "commission", "Value": "10.0", "Type": "DOUBLE"},
            {"Name": "gas_price", "Value": "1000", "Type": "DOUBLE"},
            {"Name": "curr_epoch", "Value": "769", "Type": "DOUBLE"},
            {"Name": "stake_total", "Value": "13070019.320946", "Type": "DOUBLE"},
        ],
    },
    {
        "Time": "1682473096863",
        "MeasureValues": [
            {"Name": "cpu", "Value": "6.8", "Type": "DOUBLE"},
            {"Name": "memory", "Value": "16.8", "Type": "DOUBLE"},
            {"Name": "swap", "Value": "0.3", "Type": "DOUBLE"},
            {"Name": "disk", "Value": "10.4", "Type": "DOUBLE"},
            {"Name": "db_disk", "Value": "49.9", "Type": "DOUBLE"},
            {"Name": "certificates_created", "Value": "2120", "Type": "DOUBLE"},
            {"Name": "current_round", "Value": "26043", "Type": "DOUBLE"},
            {"Name": "highest_synced_checkpoint", "Value": "2109122", "Type": "DOUBLE"},
            {"Name": "last_executed_checkpoint", "Value": "2109122", "Type": "DOUBLE"},
            {
                "Name": "last_executed_checkpoint",
                "Value": "1682473087743",
                "Type": "DOUBLE",
            },
            {"Name": "num_shared_obj_tx", "Value": "36106", "Type": "DOUBLE"},
            {
                "Name": "total_transaction_certificates",
                "Value": "144311",
                "Type": "DOUBLE",
            },
            {"Name": "uptime", "Value": "1327", "Type": "DOUBLE"},
            {"Name": "epoch_time_left", "Value": "72141856.64111328", "Type": "DOUBLE"},
            {"Name": "rewards_pool", "Value": "117622.909087535", "Type": "DOUBLE"},
            {"Name": "voting_power", "Value": "51", "Type": "DOUBLE"},
            {
                "Name": "next_epoch_stake",
                "Value": "25175396.95940239",
                "Type": "DOUBLE",
            },
            {"Name": "curr_stake", "Value": "25175180.982754085", "Type": "DOUBLE"},
            {"Name": "next_epoch_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "curr_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "commission", "Value": "10.0", "Type": "DOUBLE"},
            {"Name": "gas_price", "Value": "1000", "Type": "DOUBLE"},
            {"Name": "curr_epoch", "Value": "769", "Type": "DOUBLE"},
            {"Name": "stake_total", "Value": "13070019.320946", "Type": "DOUBLE"},
        ],
    },
    {
        "Time": "1682473102960",
        "MeasureValues": [
            {"Name": "cpu", "Value": "6.0", "Type": "DOUBLE"},
            {"Name": "memory", "Value": "16.8", "Type": "DOUBLE"},
            {"Name": "swap", "Value": "0.3", "Type": "DOUBLE"},
            {"Name": "disk", "Value": "10.4", "Type": "DOUBLE"},
            {"Name": "db_disk", "Value": "49.9", "Type": "DOUBLE"},
            {"Name": "certificates_created", "Value": "2132", "Type": "DOUBLE"},
            {"Name": "current_round", "Value": "26055", "Type": "DOUBLE"},
            {"Name": "highest_synced_checkpoint", "Value": "2109126", "Type": "DOUBLE"},
            {"Name": "last_executed_checkpoint", "Value": "2109126", "Type": "DOUBLE"},
            {
                "Name": "last_executed_checkpoint",
                "Value": "1682473091723",
                "Type": "DOUBLE",
            },
            {"Name": "num_shared_obj_tx", "Value": "36270", "Type": "DOUBLE"},
            {
                "Name": "total_transaction_certificates",
                "Value": "144945",
                "Type": "DOUBLE",
            },
            {"Name": "uptime", "Value": "1334", "Type": "DOUBLE"},
            {"Name": "epoch_time_left", "Value": "72135761.44604492", "Type": "DOUBLE"},
            {"Name": "rewards_pool", "Value": "117622.909087535", "Type": "DOUBLE"},
            {"Name": "voting_power", "Value": "51", "Type": "DOUBLE"},
            {
                "Name": "next_epoch_stake",
                "Value": "25175396.95940239",
                "Type": "DOUBLE",
            },
            {"Name": "curr_stake", "Value": "25175180.982754085", "Type": "DOUBLE"},
            {"Name": "next_epoch_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "curr_voted_gas", "Value": "980", "Type": "DOUBLE"},
            {"Name": "commission", "Value": "10.0", "Type": "DOUBLE"},
            {"Name": "gas_price", "Value": "1000", "Type": "DOUBLE"},
            {"Name": "curr_epoch", "Value": "769", "Type": "DOUBLE"},
            {"Name": "stake_total", "Value": "13070019.320946", "Type": "DOUBLE"},
        ],
    },
]
